src/O2 Chat/src/web/com.o2bionics.chat.app/Models/TestO2BionicsMock/ChatSourceViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Com.O2Bionics.ChatService.Web.Console.Models.TestO2BionicsMock
{
    public class ChatSourceViewModel
    {
        [Required]
        [EmailAddress]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Display(Name = "O2Bionics UserId")]
        public int O2BionicsUserId { get; set; }

        [Required]
        [RegularExpression("([0-9]+)", ErrorMessage = "Can contain digits only")]
        [Display(Name = "O2Bionics AccountNumber")]
        public string O2BionicsAccountNumber { get; set; }
    }
}

src/O2 Chat/src/web/com.o2bionics.chat.app/Controllers/TestO2BionicsMockController.cs
using System;
using System.Web.Mvc;
using Com.O2Bionics.ChatService.Web.Console.Models.TestO2BionicsMock;
using Com.O2Bionics.Utils;
using JetBrains.Annotations;
using Jil;

namespace Com.O2Bionics.ChatService.Web.Console.Controllers
{
    public class O2BionicsUserInfo
    {
        [JilDirective("created")]
        public DateTime CreatedTimeUtc { [UsedImplicitly] get; set; }

        [JilDirective("userId")]
        public int UserId { [UsedImplicitly] get; set; }

        [JilDirective("accountNumber")]
        public string AccountNumber { [UsedImplicitly] get; set; }

        [JilDirective("email")]
        public string Email { get; set; }

        [JilDirective("firstName")]
        public string FirstName { get; set; }

        [JilDirective("lastName")]
        public string LastName { get; set; }
    }

    public class TestO2BionicsMockController : Controller
    {
        [HttpGet]
        [AllowAnonymous]
        public ActionResult ChatSource()
        {
            var model = new ChatSourceViewModel
                {
                    Email = "test1@some.site.com",
                    FirstName = "Vasily",
                    LastName = "Pupkin",
                    O2BionicsUserId = 12345,
                    O2BionicsAccountNumber = "001234598",
                };

            return View(model);
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult ChatSource(ChatSourceViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            var userInfo = new O2BionicsUserInfo
                {
                    CreatedTimeUtc = DateTime.UtcNow,
                    UserId = model.O2BionicsUserId,
                    AccountNumber = model.O2BionicsAccountNumber,
                    Email = model.Email,
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                };
            var jsonUserInfo = userInfo.JsonStringify2();
            var key = GlobalContainer.Resolve<WorkspaceSettings>().O2BionicsSite3DesKey;
            var encrypted = O2Bionics3DesEncryptor.Enrypt(jsonUserInfo, key);
            var encryptedString = Convert.ToBase64String(encrypted);

            return RedirectToAction("RegisterCustomer", "Account", new { au = encryptedString });
        }
    }
}

src/O2 Chat/src/web/com.o2bionics.chat.app/Views/TestO2BionicsMock/ChatSource.cshtml
@model Com.O2Bionics.ChatService.Web.Console.Models.TestO2BionicsMock.ChatSourceViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>O2Bionics Mock - Chat Source</title>
</head>
<body>
<div>
    <div class="widget-foot" style="width: 700px; margin-left: auto; margin-right: auto;">
        <div class="padd">
            @using (Html.BeginForm("ChatSource", "TestO2BionicsMock", new { ViewBag.ReturnUrl }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <div class="form-group">
                    @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-lg-3" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", placeholder = Html.DisplayNameFor(m => m.FirstName), })
                        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.LastName, new { @class = "control-label col-lg-3" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", placeholder = Html.DisplayNameFor(m => m.LastName), })
                        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "control-label col-lg-3" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = Html.DisplayNameFor(m => m.Email), })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.O2BionicsUserId, new { @class = "control-label col-lg-3" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.O2BionicsUserId, new { placeholder = Html.DisplayNameFor(m => m.O2BionicsUserId), })
                        @Html.ValidationMessageFor(m => m.O2BionicsUserId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.O2BionicsAccountNumber, new { @class = "control-label col-lg-3" })
                    <div class="col-lg-9">
                        @Html.TextBoxFor(m => m.O2BionicsAccountNumber, new { placeholder = Html.DisplayNameFor(m => m.O2BionicsAccountNumber), })
                        @Html.ValidationMessageFor(m => m.O2BionicsAccountNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div>&nbsp;</div>
                <div class="form-group">
                    <div class="col-lg-9 col-lg-offset-3">
                        <input type="submit" value="Go to O2Chat Customer registration" class="btn btn-default"/>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/account/script")

</body>
</html>